Repository zimmerman-team/IATI-Humanitarian-Data-Portal, pull requests merged in 2020-03, with the labels that each got.

#218 MLT-823
  src/app/components/charts/BarCharts/HorizontalBarChart/consts.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/index.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/model.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/utils.tsx
Labels: size/L

#219 MLT-833
  src/app/components/feedback/SnackBar/CookieDialog/common/message.tsx
Labels: size/XS

#226 MLT-846.2
  .zeplin/components.json
  LICENSE.MD
  src/app/components/charts/BarCharts/HorizontalBarChart/consts.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/index.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/model.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/utils.tsx
  src/app/components/feedback/SnackBar/CookieDialog/common/message.tsx
  src/app/modules/activityDetails/common/activityHeader/index.tsx
  src/app/modules/activityDetails/layout.tsx
  src/app/modules/activityDetails/utils/formatActivityElements.ts
  src/app/modules/signatory-data/mock.ts
  src/app/modules/signatory-data/submodules/activityList/const.tsx
  src/app/modules/signatory-data/submodules/coveragePage/utils/formatTransFacets.ts
  src/app/modules/signatory-data/submodules/index.tsx
  src/app/modules/signatory-data/submodules/overview/const.ts
  src/app/modules/signatory-data/submodules/overview/index.tsx
  src/app/modules/signatory-data/submodules/overview/layout.tsx
  src/app/modules/signatory-data/submodules/overview/model.ts
  src/app/modules/signatory-data/submodules/timelines/const.ts
Labels: size/L

#223 MLT-797 MLT-798
  src/app/modules/signatory-data/submodules/coveragePage/store/interfaces.ts
  src/app/modules/signatory-data/submodules/coveragePage/utils/formatCovData.ts
  src/app/modules/signatory-data/submodules/coveragePage/utils/formatTransFacets.ts
Labels: size/M

#227 Revert "MLT-846.2"
  .zeplin/components.json
  LICENSE.MD
  src/app/components/charts/BarCharts/HorizontalBarChart/consts.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/index.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/model.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/utils.tsx
  src/app/components/feedback/SnackBar/CookieDialog/common/message.tsx
  src/app/modules/activityDetails/common/activityHeader/index.tsx
  src/app/modules/activityDetails/layout.tsx
  src/app/modules/activityDetails/utils/formatActivityElements.ts
  src/app/modules/signatory-data/mock.ts
  src/app/modules/signatory-data/submodules/activityList/const.tsx
  src/app/modules/signatory-data/submodules/coveragePage/utils/formatTransFacets.ts
  src/app/modules/signatory-data/submodules/index.tsx
  src/app/modules/signatory-data/submodules/overview/const.ts
  src/app/modules/signatory-data/submodules/overview/index.tsx
  src/app/modules/signatory-data/submodules/overview/layout.tsx
  src/app/modules/signatory-data/submodules/overview/model.ts
  src/app/modules/signatory-data/submodules/timelines/const.ts
Labels: size/L

#228 MLT-846.2
  src/app/modules/signatory-data/submodules/index.tsx
  tsconfig.json
Labels: size/S

#222 [On hold] MLT-847 | MLT-849 | MLT-850
  src/app/components/datadisplay/Table/common/MultiValuesCell/index.tsx
  src/app/modules/signatory-data/submodules/providersPage/consts.tsx
  src/app/modules/signatory-data/submodules/providersPage/index.tsx
  src/app/modules/signatory-data/submodules/providersPage/utils/getTableData.ts
  src/app/modules/signatory-data/submodules/recipients/const.tsx
  src/app/modules/signatory-data/submodules/recipients/index.tsx
  src/app/modules/signatory-data/submodules/recipients/store/interfaces.ts
Labels: size/M

#229 MLT-857
  src/app/components/datadisplay/Table/common/InfoCell/index.tsx
  src/app/components/datadisplay/Table/layout.tsx
  src/app/components/datadisplay/Tooltip/index.tsx
  src/app/components/surfaces/AppBar/index.tsx
  src/app/modules/about/layout.tsx
  src/app/modules/faqs/layout.tsx
  src/app/modules/signatory-data/submodules/activityList/layout.tsx
  src/app/modules/signatory-data/submodules/coveragePage/layout.tsx
  src/app/modules/signatory-data/submodules/incoming/layout.tsx
  src/app/modules/signatory-data/submodules/providersPage/layout.tsx
  src/app/modules/signatory-data/submodules/recipients/layout.tsx
  src/app/modules/signatory-progress/submodules/CCTRI/layout.tsx
Labels: size/L

#230 MLT-840
  src/app/modules/signatory-data/layout.tsx
  src/app/modules/signatory-data/submodules/overview/layout.tsx
Labels: size/XS

#232 fix: counts were incorrectly zero for location gazeteers
  src/app/modules/signatory-data/submodules/overview/const.ts
Labels: size/XS
