Repository zimmerman-team/IATI-Humanitarian-Data-Portal, pull requests merged in 2020-01, with the labels that each got.

#198 MLT-799
  src/app/modules/signatory-data/submodules/activityList/const.tsx
  src/app/modules/signatory-data/submodules/activityList/index.tsx
  src/app/modules/signatory-data/submodules/activityList/utils/formatActivities.ts
  src/app/state/api/interfaces/activityInterface.ts
  src/app/utils/scrollToTop.tsx
Labels: size/M

#199 MLT-773
  src/app/modules/signatory-data/submodules/index.tsx
  src/app/modules/signatory-data/submodules/overview/const.ts
  src/app/modules/signatory-data/submodules/overview/index.tsx
  src/app/modules/signatory-data/submodules/overview/utils/getHumanitarianElementsData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getYearBarChartData.ts
  src/app/modules/signatory-data/submodules/utils.ts
  src/app/state/api/actionsReducers/index.ts
Labels: size/M

#201 MLT-801
  .vscode/settings.json
  src/app/modules/activityDetails/const.tsx
  src/app/modules/activityDetails/utils/formatActivityElements.ts
  src/app/state/api/actionsReducers/codeLists.ts
  src/app/state/api/interfaces/activityInterface.ts
  src/app/state/api/interfaces/codeListsInterface.ts
  src/app/utils/initialLoad.tsx
Labels: size/L

#197 MLT-785
  .circleci/config.yml
  src/app/components/feedback/MobileDialog/index.tsx
  src/app/components/feedback/SnackBar/CookieDialog/common/message.tsx
  src/app/components/feedback/SnackBar/CookieDialog/index.tsx
  src/app/components/navigation/Drawer/index.tsx
  src/app/modules/faqs/layout.tsx
  src/app/modules/landing/layout.tsx
  src/app/theme/index.js
Labels: size/L

#202 MLT-794
  cypress/integration/mlt/landing.ts
  cypress/integration/mlt/signatory-timeliness.ts
  src/app/components/charts/DonutChart/index.tsx
  src/app/components/datadisplay/Table/layout.tsx
  src/app/components/surfaces/Cards/DonutChartCard/index.tsx
  src/app/modules/signatory-data/submodules/index.tsx
  src/app/modules/signatory-data/submodules/overview/fragments/FtsImportRelated.tsx
  src/app/modules/signatory-data/submodules/providersPage/consts.tsx
  src/app/modules/signatory-data/submodules/providersPage/layout.tsx
  src/app/state/api/actionsReducers/sigdataoverviewcurrency.ts
  src/app/utils/initialLoad.tsx
  src/app/utils/scrollToTop.tsx
Labels: size/M

#203 MLT-814
  src/app/components/datadisplay/Lists/index.tsx
Labels: size/S

#204 MLT-788
  src/app/modules/signatory-data/submodules/overview/layout.tsx
Labels: size/XS

#207 MLT-812
  src/app/modules/signatory-data/submodules/recipients/index.tsx
Labels: size/XS

#208 MLT-810
  src/app/components/datadisplay/Tooltip/index.tsx
  src/app/components/svgs/ToolTipIcon/index.tsx
  src/app/modules/signatory-data/submodules/overview/utils/getActivitySummaryData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumActFTSData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumActWLocationInfoData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumActWMultiYearFundingData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumActwGBClassificationsData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumOtherClassOfInterestData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumResultsData.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumanitarianElementsData.ts
Labels: size/M

#209 MLT-793
  src/app/components/charts/BarCharts/HorizontalBarChart/index.tsx
  src/app/components/charts/BarCharts/HorizontalBarChart/model.tsx
  src/app/components/charts/BarCharts/VerticalBarChart/index.tsx
  src/app/modules/signatory-data/layout.tsx
  src/app/modules/signatory-data/submodules/incoming/fragments/IncomingFundsFragment.tsx
  src/app/modules/signatory-data/submodules/incoming/layout.tsx
Labels: size/M

#210 MLT-817
  src/app/components/datadisplay/Table/mock.tsx
  src/app/index.tsx
  src/app/modules/about/layout.tsx
  src/app/modules/activityDetails/const.tsx
  src/app/modules/faqs/layout.tsx
  src/app/modules/privacy/layout.tsx
  src/app/modules/signatory-data/layout.tsx
  src/app/modules/signatory-data/submodules/activityList/index.tsx
  src/app/modules/signatory-data/submodules/activityList/layout.tsx
  src/app/modules/signatory-data/submodules/incoming/fragments/IncomingFundsFragment.tsx
  src/app/modules/signatory-data/submodules/outgoing/fragments/ExpenditureFragment.tsx
  src/app/modules/signatory-data/submodules/overview/fragments/FinancialReporting.tsx
  src/app/modules/signatory-data/submodules/overview/fragments/FtsImportRelated.tsx
  src/app/modules/signatory-data/submodules/overview/layout.tsx
  src/app/modules/signatory-data/submodules/providersPage/layout.tsx
  src/app/modules/signatory-data/submodules/recipients/layout.tsx
  src/app/modules/signatory-data/submodules/timelines/layout.tsx
  src/app/modules/signatory-progress/layout.tsx
Labels: size/L

#211 MLT-816
  src/app/components/charts/LineChart/common/Legend.tsx
  src/app/components/charts/LineChart/index.tsx
  src/app/components/charts/LineChart/model.ts
  src/app/modules/signatory-progress/layout.tsx
Labels: size/L

#212 MLT-821
  package.json
  src/app/components/datadisplay/TableWTotal/style.tsx
  src/app/modules/activityDetails/common/decoration/DecoDetailMidLeft.tsx
  src/app/modules/activityDetails/common/decoration/DecoDetailMidRight.tsx
  src/app/modules/activityDetails/common/decoration/DecoDetailTopLeft.tsx
  src/app/modules/activityDetails/const.tsx
  src/app/modules/activityDetails/layout.tsx
Labels: size/L

#215 MLT-822
  src/app/modules/signatory-data/layout.tsx
  src/app/modules/signatory-data/mock.ts
  src/app/modules/signatory-data/submodules/coveragePage/layout.tsx
  src/app/modules/signatory-data/submodules/index.tsx
  src/app/modules/signatory-data/submodules/overview/index.tsx
  src/app/modules/signatory-data/submodules/overview/layout.tsx
  src/app/modules/signatory-data/submodules/overview/model.ts
  src/app/modules/signatory-data/submodules/overview/utils/getDescription.ts
  src/app/modules/signatory-data/submodules/overview/utils/getHumanitarianElementsData.ts
  src/app/modules/signatory-data/submodules/routes.tsx
Labels: size/M

#216 MLT-768 MLT-802
  src/app/modules/common/PageLoader/index.tsx
  src/app/modules/signatory-data/submodules/providersPage/common/CustomFooter/index.tsx
  src/app/modules/signatory-data/submodules/providersPage/consts.tsx
  src/app/modules/signatory-data/submodules/providersPage/index.tsx
  src/app/modules/signatory-data/submodules/providersPage/layout.tsx
  src/app/modules/signatory-data/submodules/providersPage/utils/getBarChartData.ts
  src/app/modules/signatory-data/submodules/recipients/const.tsx
  src/app/modules/signatory-data/submodules/recipients/index.tsx
  src/app/modules/signatory-data/submodules/recipients/layout.tsx
  src/app/modules/signatory-data/submodules/recipients/store/interfaces.ts
Labels: size/L

#214 MLT-815
  src/app/components/charts/BarCharts/HorizontalBarChart/model.tsx
  src/app/components/navigation/Drawer/index.tsx
  src/app/modules/about/layout.tsx
  src/app/modules/landing/common/StatContainer/Stat.tsx
  src/app/modules/landing/common/StatContainer/StatContainer.tsx
  src/app/modules/landing/layout.tsx
  src/app/modules/signatory-data/index.tsx
  src/app/modules/signatory-data/submodules/activityList/layout.tsx
  src/app/modules/signatory-progress/const.tsx
  src/app/modules/signatory-progress/index.tsx
Labels: size/L

#217 MLT-825
  package.json
  src/app/components/datadisplay/Table/helpers.tsx
  src/app/components/datadisplay/Table/index.tsx
  src/app/components/datadisplay/Table/mock.tsx
  src/app/modules/activityDetails/const.tsx
  src/app/modules/signatory-data/index.tsx
  src/app/modules/signatory-data/submodules/activityList/const.tsx
  src/app/modules/signatory-data/submodules/activityList/index.tsx
  src/app/modules/signatory-data/submodules/activityList/layout.tsx
  src/app/modules/signatory-data/submodules/coveragePage/const.ts
  src/app/modules/signatory-data/submodules/providersPage/consts.tsx
  src/app/modules/signatory-progress/const.tsx
  yarn.lock
Labels: size/M
